apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::010526250202:role/eksctl-ticketing-cluster-nodegroup-NodeInstanceRole-erdDJe0r7IaF
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::010526250202:user/jenkins-new-user
      username: jenkins-new-user
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-11T05:33:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1385"
  uid: 00741a48-ec17-43d0-9b79-15ba366b8b08
