apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: janindujm/auth
          imagePullPolicy: IfNotPresent
     # imagePullSecrets:
      #  - name: ecr-secret # Reference the secret we created earlier

---
apiVersion: v1
kind: Service
metadata:
  name: auth-ser
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
